---
- name: update web and nfs servers
 hosts: webservers, nfs
 become: yes
 tasks:
   - name: ensure wireshark is the latest version
     yum:
       name: wireshark
       state: latest

- name: update lb and db server
 hosts: lb, db
 become: yes
 tasks:
   - name: Update apt repo
     apt:
       update_cache: yes

   - name: ensure wireshark is the latest version
     apt:
       name: wireshark
       state: latest